/*
 *  This file is part of Greeklish to Greek Converter.
 * 
 *  Greeklish to Greek Converter is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  Greeklish to Greek Converter is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with Greeklish to Greek Converter.  If not, see <http://www.gnu.org/licenses/>.
 */
package greeklish2greek;

/**
 *
 * @author George Ioakeimidis <giorgosioak95 at gmail.com>
 */
public class GUI extends javax.swing.JFrame {
    
    
    javax.swing.ImageIcon img_logo = new javax.swing.ImageIcon(getClass().getResource("/images/logo32.png"));
    final javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    About about_dialog = new About(this, rootPaneCheckingEnabled);
    Converter conv;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.conv = new Converter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        open_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        convert_button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        about_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Greeklish to Greek Converter");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(img_logo.getImage());
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        open_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search32.png"))); // NOI18N
        open_button.setText("Open");
        open_button.setFocusable(false);
        open_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        open_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        open_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                open_buttonMouseClicked(evt);
            }
        });
        toolbar.add(open_button);

        jSeparator1.setForeground(new java.awt.Color(240, 240, 240));
        toolbar.add(jSeparator1);

        convert_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/convert32.png"))); // NOI18N
        convert_button.setText("Convert");
        convert_button.setFocusable(false);
        convert_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        convert_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        convert_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convert_buttonMouseClicked(evt);
            }
        });
        toolbar.add(convert_button);

        jSeparator2.setForeground(new java.awt.Color(240, 240, 240));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setEnabled(false);
        toolbar.add(jSeparator2);

        about_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about32.png"))); // NOI18N
        about_button.setText("About");
        about_button.setFocusable(false);
        about_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        about_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        about_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_buttonMouseClicked(evt);
            }
        });
        toolbar.add(about_button);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void open_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_buttonMouseClicked
        jTextArea1.setText("");
        int returnVal = fc.showOpenDialog(GUI.this);

        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File greeklishText = fc.getSelectedFile();
            java.io.BufferedReader in = null;
            try {
                in = new java.io.BufferedReader(new java.io.FileReader(greeklishText));
                String str;
                while ((str = in.readLine()) != null) {
                    jTextArea1.append(str);
                    jTextArea1.append("\n");
                }
            } catch (java.io.IOException e) {
            } finally {
                try { in.close(); } catch (Exception ex) { }
            }
        }
          
    }//GEN-LAST:event_open_buttonMouseClicked

    private void convert_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convert_buttonMouseClicked
        jTextArea2.setText("");
        String greeklish = jTextArea1.getText();
        String greek = conv.convertText(greeklish);
        jTextArea2.setText(greek);
    }//GEN-LAST:event_convert_buttonMouseClicked

    private void about_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_buttonMouseClicked

        about_dialog.show();

    }//GEN-LAST:event_about_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_button;
    private javax.swing.JButton convert_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton open_button;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
